[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
cbor4ii = { version = "0.3.2", features = ["use_std", "serde1"] }
chrono = "0.4"
protocol = { path = "../protocol" }
rusqlite = { version = "0.30.0", features = ["bundled"] }
serde = { version = "1.0", features = ["derive"] }
strum = "0.26"
strum_macros = "0.26"
zstd = "0.13.0"
